GET http://localhost:9090/logout
Accept: application/json

###

POST http://localhost:9090/login
Content-Type: application/x-www-form-urlencoded

username=jia&password=123456
###

GET http://localhost:9090/getAuthentication
Accept: application/json
###

GET http://localhost:9090/refresh
Accept: */*
Cache-Control: no-cache

###
GET http://localhost:9090/developer
Accept: */*
Cache-Control: no-cache
###

GET http://localhost:9090/admin
Accept: */*
Cache-Control: no-cache
###

GET http://localhost:9090/user
Accept: */*
Cache-Control: no-cache
###